---
# tasks file for sandy.init
- hostname:
    name: "{{ item }}"
  with_items: "{{ inventory_hostname }}"

# install dependencies
- name: install yum packages as present
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - "{{ yum_packages }}"

# - shell: nmcli con show
#   register: nmcli_output

# - debug:
#     var: nmcli_output


- name: print default variable
  debug:
    var: base_interface

- name: print variables ethernet
  debug: 
    var: ethernet
    verbosity: 3

# issues here for some reason 

# alias 
- name: nmcli add Ethernet - conn_name only & ip4 gw4
  nmcli:
    type: ethernet
    conn_name: '{{ item.ifname }}:{{ item.conn_name }}'     # This will be the name of the file
    ifname: '{{ item.ifname }}'
    ip4: '{{ item.ip4 | ipaddr }}'
    gw4: '{{ item.gw4 | ipaddr }}'
    state: present
    autoconnect: yes
  with_items:
    - '{{ ethernet }}'
  when: item.ip4 is defined
  notify: restart interfaces

# configure a service restart using the handlers
#  add notify:  label_space to the roles handlers
- name: ping the gateway
  command: /bin/ping -c1 "{{ item }}"
  ignore_errors: yes
  with_items:
    - "{{ gateway }}"

- name: sshd configure not to allow root login
  lineinfile:
    path: "/etc/ssh/sshd_config"
    owner: root
    mode: 0600
    state: present
    regexp: '^PermitRootLogin\s*yes'
    line: "#PermitRootLogin yes"
    backrefs: yes
