---
# init.yaml
# the sandbox tasks reference README.md
- hosts: all
  become: true
  gather_facts: false
  tasks:
  - name: Run the sandy.init role on all nodes
    include_role:
      name: sandy.init

- hosts: all:!controller
  become: true
  gather_facts: false
  tasks:
  - name: Run sandy.init_remotes role on all the non controller nodes
    include_role:
      name: sandy.init_remotes