---
# vars file for sandy.init
gateway:
  storage_gw: "192.168.70.1"
  external_gw: "192.168.80.1"
  tenant_gw: "192.168.90.1"

ethernet:
  # tenant
  - conn_name: tenant
    ifname: eth4
    ip4: "{{ tenant_ip }}"
    gw4: "{{ gateway.tenant_gw }}"
  # external
  - conn_name: external
    ifname: eth3
    ip4: "{{ external_ip }}"
    gw4: "{{ gateway.external_gw }}"
  # storage
  - conn_name: storage
    ifname: eth2
    ip4: "{{ storage_ip }}"
    gw4: "{{ gateway.storage_gw }}"

yum_packages:
  - NetworkManager-glib
  # - libnm-qt-devel.x86_64
  # - nm-connection-editor.x86_64
  # - libsemanage-python
  # - policycoreutils-python
